

@startuml 
title manage_post_flowchart
|User|
start
if(choose manage action) then (create post)  
: click on create post ;  
: fill in the post information ; 
: adjust the post setting  ; 
: click create post ; 
|#lightgray|System| 
: create post ; 
|User|
else(modifile post)
: click on a post edit button  ; 
: change the post information ;
: change the post setting ;
: click save post ; 
|#lightgray|System| 
: update post ; 
endif 
' : notify the admin of the post report ;  
|User|
: show message notifying  success ; 
stop

@enduml
