@startuml 
title Report Post Flowchart
|User|
start
: Choose Report Category  ; 
: Fill In Report Message  ;  
: Click Send Report;  
|#lightgray|System|
: Notify The Admin Of The Reported Post ;  
stop
@enduml
