@startuml 
title View Post Flowchart
|User|
start
:View Post ;
if (Click Report Button)  then  (Yes) 
:Report Post Flowchart|
else(Engage With Post)
    if(Like) then (Yes)
    : Click Post Like Button ; 
    else(Comment) 
    : Click Comment Button  ; 
    : Fill In The Comment Text Area; 
    : Click Post comment ;
    endif 
endif 
|#lightgray|System|
:Update Post Changes;
stop
@enduml
