@startuml 
title Login User Flowchart
|User|
start
repeat: Fill In Login Credential ; 
: Click Login;  
|#lightgray|System|
backward:Show Error Message;
repeat while(Info  Is Valid) is (No) not (Yes)
:Redirected To User Homepage;
stop
@enduml
