@startuml 
title Recover Password Flowchart
|User|
start
repeat: Click  Forgotten  Password; 
: Notify The User Of  Verifying By Email ;
repeat while(User Accept Verification Method) is (No) not (Yes)
|#lightgray|System| 
: Send Confirmation Email  ;  
|User| 
: Verify Email Address; 
repeat: Create New Password  ; 
: Change Password ; 
|#lightgray|System| 
repeat while(Verify Password) is (No) not (Yes)
|#lightgray|System| 
: Update Password ; 
stop
@enduml
