@startuml 
title recover_password_flowchart
|User|
start
repeat: click  on  forgotten  password; 
: notify the user of  verifying by email ;
repeat while(user accept verification method) is (no) not (yes)
|#lightgray|System| 
: send confirmation email  ;  
|User| 
: verify email address; 
repeat: create new password  ; 
: change password ; 
repeat while(verify password) is (no) not (yes)
|#lightgray|System| 
: update password ; 
stop
@enduml
