@startuml 
title View Person Flowchart
|User|
start
:Click On A Person Profile ; 
|#lightgray|System|
:Redirected To Person Page ; 
|User| 
if(Relationship) then (Yes)
    if(Add Friend) then (Yes)

        :Add Friend To User Group ; 
    else(Unfriend)
        :Remove Person From User Friend Group; 
    endif
else (Status)  
    if(Block) then (Yes)
        :Block Person ; 
    else(Unblock)
        :Unblock Person ; 
    endif
endif
|#lightgray|System|
:Update Person Changes ; 
stop
@enduml
